### ISSUE TITLE
Trace checking in python API

### ISSUE THREAD

**Issue by MFaisalZaki** [black-sat/black#121]
The documentation shows how to use black python's API but does not show how to check a trace using the API. Do you know if this functionality is supported?

**Comment by nicola-gigante** [comment]
Hi!

In the stable version (0.10.7), trace checking is implemented as part of the frontend CLI command, not in the library, and as such it is not exposed by the Python API.

But the Python API is not documented for the stable version, so are you looking at the `development` branch? 
In this case, trace checking is not implemented (yet) in that branch.

Let me know if you need other information.

**Comment by MFaisalZaki** [comment]
Hi @nicola-gigante thanks for highlighting this. Are there any plans to include the check in the Python API anytime soon? If not, can you recommend alternative Python libraries I can use?

**Comment by nicola-gigante** [comment]
Not so soon, but it will be supported once the `development` branch will be merged, although I don't have a time horizon because that branch is undergoing a major refactoring.

With more details I may be able to help you more. For example, note that the trace checking feature in the command-line tool supports reading the trace from a JSON and supports providing the answer in JSON, that you can indeed parse and produce with Python.

**Comment by MFaisalZaki** [comment]
That is a good idea. Will give it a try. Thank you 😊

**Comment by nicola-gigante** [comment]
You are welcome!
