### ISSUE TITLE
Fresh installation error on Z3 

### ISSUE THREAD

**Issue by germanbraun** [black-sat/black#38]
I tried a new fresh installation but I got this error:
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Z3 (missing: Z3_LIBRARY Z3_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZ3.cmake:44 (find_package_handle_standard_args)
  src/lib/CMakeLists.txt:30 (find_package)
```

however, i understand that Z3 is an optional dependency

**Comment by nicola-gigante** [comment]
Hi! I'm sorry, this has changed right under your feet. Because of recent problems with the Glucose backend (some bugs in the CNF encoding and some really slow performance on some new class of test formulas with past operators), today I switched the default backend to Z3. 

As a consequence, it is required to build the tool, even if other backends are found. A way to select the default backend on build-time is still missing. That is hopefully not a big problem since both debian-based and rpm-based distributions have prebuilt packages of Z3 in their repos.
